<a href="https://colab.research.google.com/github/Sbbarse787/Heart-diseases-predictions-using-Keras-and-pandas/blob/master/Keras_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive # Mount Colab to Your gdrive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive

In [ ]:
cd /gdrive/My Drive/Colab Notebooks/SAS  #Specify the Location of your data set

/gdrive/My Drive/Colab Notebooks/SAS

In [ ]:
import pandas as pd
df = pd.read_csv('heart.csv'    #Read the dataset using pandas
)

In [ ]:
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [ ]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
X = df.iloc[:,0:13]       #Slicing of data set..X=[1,....13]
y = df.iloc[:,-1]          #Y=[Target variable]

In [ ]:
from sklearn.model_selection import train_test_split     #Split the data set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler     #Standerisation of dataset
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
pip install --upgrade keras   #install keras

Collecting keras
  Downloading https://files.pythonhosted.org/packages/ad/fd/6bfe87920d7f4fd475acd28500a42482b6b84479832bdc0fe9e589a60ceb/Keras-2.3.1-py2.py3-none-any.whl (377kB)
     |████████████████████████████████| 378kB 2.5MB/s
Requirement already satisfied, skipping upgrade: h5py in /usr/local/lib/python3.6/dist-packages (from keras) (2.10.0)
Requirement already satisfied, skipping upgrade: scipy>=0.14 in /usr/local/lib/python3.6/dist-packages (from keras) (1.4.1)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python3.6/dist-packages (from keras) (3.13)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from keras) (1.12.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from keras) (1.1.0)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from keras) (1.0.8)
Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in /usr/local/lib/python3.6/dist-packages (from keras) (1.18.2)
Installing collected packages: keras
  Found existing installation: Keras 2.2.5
    Uninstalling Keras-2.2.5:
      Successfully uninstalled Keras-2.2.5
Successfully installed keras-2.3.1

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier=Sequential()
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=13)) # add the layers in neural network..
classifier.add(keras.layers.Dropout(0.4))
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier.add(keras.layers.Dropout(0.4))
classifier.add(Dense(units=1,activation='sigmoid'))
classifier.compile(optimizer='adagrad',loss='binary_crossentropy',metrics=['accuracy'])
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Using TensorFlow backend.

Epoch 1/100
242/242 [==============================] - 0s 1ms/step - loss: 0.6902 - accuracy: 0.5372
Epoch 2/100
242/242 [==============================] - 0s 132us/step - loss: 0.6675 - accuracy: 0.6818
Epoch 3/100
242/242 [==============================] - 0s 120us/step - loss: 0.6387 - accuracy: 0.6446
Epoch 4/100
242/242 [==============================] - 0s 112us/step - loss: 0.6007 - accuracy: 0.7107
Epoch 5/100
242/242 [==============================] - 0s 120us/step - loss: 0.5836 - accuracy: 0.7066
Epoch 6/100
242/242 [==============================] - 0s 119us/step - loss: 0.5488 - accuracy: 0.7479
Epoch 7/100
242/242 [==============================] - 0s 122us/step - loss: 0.5343 - accuracy: 0.7066
Epoch 8/100
242/242 [==============================] - 0s 116us/step - loss: 0.5180 - accuracy: 0.7190
Epoch 9/100
242/242 [==============================] - 0s 123us/step - loss: 0.5098 - accuracy: 0.7314
Epoch 10/100
242/242 [==============================] - 0s 137us/step - loss: 0.5429 - accuracy: 0.6942
Epoch 11/100
242/242 [==============================] - 0s 119us/step - loss: 0.5033 - accuracy: 0.6942
Epoch 12/100
242/242 [==============================] - 0s 125us/step - loss: 0.5005 - accuracy: 0.7190
Epoch 13/100
242/242 [==============================] - 0s 135us/step - loss: 0.5215 - accuracy: 0.7893
Epoch 14/100
242/242 [==============================] - 0s 120us/step - loss: 0.5162 - accuracy: 0.7686
Epoch 15/100
242/242 [==============================] - 0s 136us/step - loss: 0.4809 - accuracy: 0.8140
Epoch 16/100
242/242 [==============================] - 0s 121us/step - loss: 0.4691 - accuracy: 0.8099
Epoch 17/100
242/242 [==============================] - 0s 130us/step - loss: 0.4844 - accuracy: 0.7851
Epoch 18/100
242/242 [==============================] - 0s 127us/step - loss: 0.4943 - accuracy: 0.8017
Epoch 19/100
242/242 [==============================] - 0s 124us/step - loss: 0.4829 - accuracy: 0.8140
Epoch 20/100
242/242 [==============================] - 0s 116us/step - loss: 0.4912 - accuracy: 0.7769
Epoch 21/100
242/242 [==============================] - 0s 117us/step - loss: 0.4747 - accuracy: 0.7975
Epoch 22/100
242/242 [==============================] - 0s 113us/step - loss: 0.5126 - accuracy: 0.7727
Epoch 23/100
242/242 [==============================] - 0s 120us/step - loss: 0.4774 - accuracy: 0.7645
Epoch 24/100
242/242 [==============================] - 0s 116us/step - loss: 0.4852 - accuracy: 0.7810
Epoch 25/100
242/242 [==============================] - 0s 115us/step - loss: 0.4581 - accuracy: 0.8223
Epoch 26/100
242/242 [==============================] - 0s 118us/step - loss: 0.4879 - accuracy: 0.7893
Epoch 27/100
242/242 [==============================] - 0s 118us/step - loss: 0.4596 - accuracy: 0.8017
Epoch 28/100
242/242 [==============================] - 0s 121us/step - loss: 0.4464 - accuracy: 0.8017
Epoch 29/100
242/242 [==============================] - 0s 117us/step - loss: 0.4837 - accuracy: 0.7810
Epoch 30/100
242/242 [==============================] - 0s 113us/step - loss: 0.4863 - accuracy: 0.7769
Epoch 31/100
242/242 [==============================] - 0s 129us/step - loss: 0.4760 - accuracy: 0.8140
Epoch 32/100
242/242 [==============================] - 0s 117us/step - loss: 0.5090 - accuracy: 0.7686
Epoch 33/100
242/242 [==============================] - 0s 119us/step - loss: 0.4449 - accuracy: 0.7851
Epoch 34/100
242/242 [==============================] - 0s 121us/step - loss: 0.4945 - accuracy: 0.7686
Epoch 35/100
242/242 [==============================] - 0s 119us/step - loss: 0.4651 - accuracy: 0.8140
Epoch 36/100
242/242 [==============================] - 0s 128us/step - loss: 0.4726 - accuracy: 0.7810
Epoch 37/100
242/242 [==============================] - 0s 158us/step - loss: 0.4632 - accuracy: 0.7975
Epoch 38/100
242/242 [==============================] - 0s 143us/step - loss: 0.4758 - accuracy: 0.7810
Epoch 39/100
242/242 [==============================] - 0s 136us/step - loss: 0.4746 - accuracy: 0.8264
Epoch 40/100
242/242 [==============================] - 0s 137us/step - loss: 0.4721 - accuracy: 0.7893
Epoch 41/100
242/242 [==============================] - 0s 149us/step - loss: 0.4706 - accuracy: 0.8140
Epoch 42/100
242/242 [==============================] - 0s 128us/step - loss: 0.4510 - accuracy: 0.8223
Epoch 43/100
242/242 [==============================] - 0s 138us/step - loss: 0.4279 - accuracy: 0.7893
Epoch 44/100
242/242 [==============================] - 0s 130us/step - loss: 0.4654 - accuracy: 0.7893
Epoch 45/100
242/242 [==============================] - 0s 118us/step - loss: 0.4490 - accuracy: 0.8099
Epoch 46/100
242/242 [==============================] - 0s 113us/step - loss: 0.4670 - accuracy: 0.7727
Epoch 47/100
242/242 [==============================] - 0s 112us/step - loss: 0.4609 - accuracy: 0.8264
Epoch 48/100
242/242 [==============================] - 0s 125us/step - loss: 0.4510 - accuracy: 0.8264
Epoch 49/100
242/242 [==============================] - 0s 121us/step - loss: 0.4284 - accuracy: 0.8017
Epoch 50/100
242/242 [==============================] - 0s 121us/step - loss: 0.4537 - accuracy: 0.8306
Epoch 51/100
242/242 [==============================] - 0s 132us/step - loss: 0.4715 - accuracy: 0.7934
Epoch 52/100
242/242 [==============================] - 0s 136us/step - loss: 0.4680 - accuracy: 0.8058
Epoch 53/100
242/242 [==============================] - 0s 133us/step - loss: 0.4607 - accuracy: 0.7975
Epoch 54/100
242/242 [==============================] - 0s 127us/step - loss: 0.4467 - accuracy: 0.8182
Epoch 55/100
242/242 [==============================] - 0s 124us/step - loss: 0.4618 - accuracy: 0.7769
Epoch 56/100
242/242 [==============================] - 0s 142us/step - loss: 0.4609 - accuracy: 0.8017
Epoch 57/100
242/242 [==============================] - 0s 113us/step - loss: 0.4853 - accuracy: 0.8058
Epoch 58/100
242/242 [==============================] - 0s 118us/step - loss: 0.4723 - accuracy: 0.7603
Epoch 59/100
242/242 [==============================] - 0s 121us/step - loss: 0.4692 - accuracy: 0.8099
Epoch 60/100
242/242 [==============================] - 0s 116us/step - loss: 0.4498 - accuracy: 0.7810
Epoch 61/100
242/242 [==============================] - 0s 119us/step - loss: 0.4667 - accuracy: 0.7893
Epoch 62/100
242/242 [==============================] - 0s 115us/step - loss: 0.4644 - accuracy: 0.7810
Epoch 63/100
242/242 [==============================] - 0s 120us/step - loss: 0.4752 - accuracy: 0.7769
Epoch 64/100
242/242 [==============================] - 0s 115us/step - loss: 0.4639 - accuracy: 0.8182
Epoch 65/100
242/242 [==============================] - 0s 119us/step - loss: 0.4572 - accuracy: 0.8058
Epoch 66/100
242/242 [==============================] - 0s 118us/step - loss: 0.4800 - accuracy: 0.7934
Epoch 67/100
242/242 [==============================] - 0s 120us/step - loss: 0.4455 - accuracy: 0.8182
Epoch 68/100
242/242 [==============================] - 0s 134us/step - loss: 0.4023 - accuracy: 0.8347
Epoch 69/100
242/242 [==============================] - 0s 136us/step - loss: 0.4507 - accuracy: 0.8140
Epoch 70/100
242/242 [==============================] - 0s 135us/step - loss: 0.4710 - accuracy: 0.8430
Epoch 71/100
242/242 [==============================] - 0s 123us/step - loss: 0.4434 - accuracy: 0.8140
Epoch 72/100
242/242 [==============================] - 0s 116us/step - loss: 0.4947 - accuracy: 0.7893
Epoch 73/100
242/242 [==============================] - 0s 137us/step - loss: 0.4614 - accuracy: 0.8058
Epoch 74/100
242/242 [==============================] - 0s 119us/step - loss: 0.4630 - accuracy: 0.7810
Epoch 75/100
242/242 [==============================] - 0s 112us/step - loss: 0.4857 - accuracy: 0.7727
Epoch 76/100
242/242 [==============================] - 0s 117us/step - loss: 0.4534 - accuracy: 0.8430
Epoch 77/100
242/242 [==============================] - 0s 117us/step - loss: 0.4095 - accuracy: 0.8182
Epoch 78/100
242/242 [==============================] - 0s 119us/step - loss: 0.4738 - accuracy: 0.7727
Epoch 79/100
242/242 [==============================] - 0s 114us/step - loss: 0.4332 - accuracy: 0.8264
Epoch 80/100
242/242 [==============================] - 0s 129us/step - loss: 0.4664 - accuracy: 0.8306
Epoch 81/100
242/242 [==============================] - 0s 133us/step - loss: 0.4366 - accuracy: 0.8223
Epoch 82/100
242/242 [==============================] - 0s 138us/step - loss: 0.4637 - accuracy: 0.7810
Epoch 83/100
242/242 [==============================] - 0s 154us/step - loss: 0.4610 - accuracy: 0.8017
Epoch 84/100
242/242 [==============================] - 0s 151us/step - loss: 0.4737 - accuracy: 0.7934
Epoch 85/100
242/242 [==============================] - 0s 132us/step - loss: 0.4567 - accuracy: 0.7975
Epoch 86/100
242/242 [==============================] - 0s 112us/step - loss: 0.4459 - accuracy: 0.8017
Epoch 87/100
242/242 [==============================] - 0s 127us/step - loss: 0.4934 - accuracy: 0.7562
Epoch 88/100
242/242 [==============================] - 0s 111us/step - loss: 0.4232 - accuracy: 0.8017
Epoch 89/100
242/242 [==============================] - 0s 122us/step - loss: 0.4384 - accuracy: 0.8140
Epoch 90/100
242/242 [==============================] - 0s 125us/step - loss: 0.4631 - accuracy: 0.8182
Epoch 91/100
242/242 [==============================] - 0s 117us/step - loss: 0.4450 - accuracy: 0.8099
Epoch 92/100
242/242 [==============================] - 0s 109us/step - loss: 0.4420 - accuracy: 0.8017
Epoch 93/100
242/242 [==============================] - 0s 116us/step - loss: 0.4712 - accuracy: 0.8017
Epoch 94/100
242/242 [==============================] - 0s 113us/step - loss: 0.4480 - accuracy: 0.8264
Epoch 95/100
242/242 [==============================] - 0s 111us/step - loss: 0.4439 - accuracy: 0.8099
Epoch 96/100
242/242 [==============================] - 0s 117us/step - loss: 0.4484 - accuracy: 0.8058
Epoch 97/100
242/242 [==============================] - 0s 115us/step - loss: 0.4651 - accuracy: 0.8140
Epoch 98/100
242/242 [==============================] - 0s 113us/step - loss: 0.4318 - accuracy: 0.8099
Epoch 99/100
242/242 [==============================] - 0s 113us/step - loss: 0.4293 - accuracy: 0.8182
Epoch 100/100
242/242 [==============================] - 0s 117us/step - loss: 0.4511 - accuracy: 0.7934

In [ ]:
df.head(10)

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1
5   57    1   0       140   192    0  ...      0      0.4      1   0     1       1
6   56    0   1       140   294    0  ...      0      1.3      1   0     2       1
7   44    1   1       120   263    0  ...      0      0.0      2   0     3       1
8   52    1   2       172   199    1  ...      0      0.5      2   0     3       1
9   57    1   2       150   168    0  ...      0      1.6      2   0     2       1

[10 rows x 14 columns]

In [ ]:
df.tail(10)

     age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
293   67    1   2       152   212    0  ...      0      0.8      1   0     3       0
294   44    1   0       120   169    0  ...      1      2.8      0   0     1       0
295   63    1   0       140   187    0  ...      1      4.0      2   2     3       0
296   63    0   0       124   197    0  ...      1      0.0      1   0     2       0
297   59    1   0       164   176    1  ...      0      1.0      1   2     1       0
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[10 rows x 14 columns]

In [ ]:
import numpy as np

In [ ]:
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)
n=[44,1,0,120,169,0,1,144,1,2.8,0,0,1] #Add input of arrays to the model....
prediction=classifier.predict(sc.transform(np.array([n])))  #Prediction of dataset 
prediction=(prediction>0.5)
print(prediction)

[[False]]

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[22  5]
 [ 3 31]]

In [2]:
def accuracy():
  x=22+31
  y=22+31+5+3
  return (x/y)*100
print(accuracy())

86.88524590163934

**At the end we get the accuracy of 86.885%**